### ISSUE TITLE
Correct WARNINGS when generating the spec document

### ISSUE THREAD

**Issue by pnicolucci** [eclipse-ee4j/jstl-api#120]
>  --- asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc (asciidoc-to-html) @ jakarta-stl-spec ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] Copying 1 resource
> [INFO] asciidoctor: WARN: license-efsl.adoc: line 14: section title out of sequence: expected levels 0 or 1, got level 2
> [INFO] Rendered C:\jakartaGit\jstl-api\spec\src\main\asciidoc\jakarta-stl-spec.adoc
> [INFO]
> [INFO] --- asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc (asciidoc-to-pdf) @ jakarta-stl-spec ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] Copying 1 resource
> [INFO] asciidoctor: WARN: license-efsl.adoc: line 14: section title out of sequence: expected levels 0 or 1, got level 2
> [INFO] asciidoctor: WARN: Could not locate the character `' in the following fonts: M+ 1mn, M+ 1p Fallback
> [INFO] Rendered C:\jakartaGit\jstl-api\spec\src\main\asciidoc\jakarta-stl-spec.adoc
>

**Comment by arjantijms** [comment]
It should be simple, I corrected this a couple of times before. It's just the copyright header at level 2 that's missing. See e.g. https://github.com/eclipse-ee4j/authorization/blob/master/spec/src/main/asciidoc/license-efsl.adoc#copyright

**Comment by pnicolucci** [comment]
It looks like the WARN regarding the character issue was introduced as part of https://github.com/eclipse-ee4j/jstl-api/commit/de2deae3428eb09bb74ad672f28ea5e1cd314226#diff-16b376b1e09deeb28d3bfb443bc6e7d6 as far as I can tell.

I'm working through that change to see what happened and correct it as well as part of this issue.

**Comment by pnicolucci** [comment]
Regarding the character issue I can't for the life of me determine why asciidoc complains about this. Looking at the rendered code it looks to be 100% correct. For now I think we can leave it be as it looks to be caused by the footnote in the literal block but it renders successfully as far as I can tell.

**Comment by pnicolucci** [comment]
If I were to use a literal block sub of `macros+` rather then `+macros` I can see the footnote syntax added in the pdf and that is:

```
<x:parse {doc="XMLDocument"|xml<a id="_footnoteref_10">􀀀</a><sup>[<a
anchor="_footnotedef_10">10</a>]</sup>="XMLDocument"}
{var="var" [scope="scope"]|varDom="var"
[scopeDom="scope"]}
[systemId="systemId"]
[filter="filter"]/>
```

You can see  there is an odd character  but it doesn't render in the final product using `+macros` substitution but we still get a warning it seems. Perhaps this is a bug with asciidoc?

**Comment by arjantijms** [comment]
@pnicolucci good find. I'm not sure if we absolutely need the footnote as it is. It would need to be handled in the next version of Jakarta Tags I think.

**Comment by pnicolucci** [comment]
Only remaining warning is: 

```
[INFO] --- asciidoctor-maven-plugin:2.2.1:process-asciidoc (asciidoc-to-pdf) @ jakarta-stl-spec ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO] asciidoctor: WARN: Could not locate the character `' in the following fonts: M+ 1mn, M+ 1p Fallback
[INFO] Converted C:\jakartaGit\jstl-api\spec\src\main\asciidoc\jakarta-stl-spec.adoc
```

**Comment by pnicolucci** [comment]
Pushing this out into a future release, see thread [here](https://www.eclipse.org/lists/jstl-dev/msg00106.html).
